### ISSUE TITLE
운영 및 공부 방향 및 진도에 대한 설정

### ISSUE THREAD

**Issue by dltkr77** [hackpupu/LML#5]
개인별로 운영 방향 및 공부 방향에 대한 설정 및 논의가 필요합니다.
각자가 생각하는 바를 Comment로 남겨서 의논을 하였으면 합니다.

- [x] 운영 방향 설정
- [x] 공부 방향 설정
- [x] 진도 설정

**Comment by cd80** [comment]
[운영 방향]
2월 한달동안 각자 하고 있는 공부를, 실제로 머신러닝에 대한 원리적 이해가 필요한 단계로 진전 시킵니다
그래서 3월부터는 모두가 만족스럽게 머신러닝을 공부할 수 있도록 하고 스터디가 아직 기초 수준인만큼 가시적인 성과, 진도를 위해 수많은 머신러닝 책들을 도서관이나 교보문고에서 2~3시간정도 검토해보고 스터디의 첫 목표를 그 정한 책을 완파하는 것으로 합니다
책을 읽다보면 사람마다 다르게 아쉬워하는 부분이 생기거나 혹은 자신이 하고 있던 다른 공부나 일에 대한 재밌는 아이디어가 떠오릅니다. 즉 프로젝트가 가능해지고 원하는  특정 프로젝트에 대한 논문을 찾아 읽을 수 있게 됩니다. 그래서 이 이후로는 다시 우리 첫 모임때처럼 자율 프로젝트, 격주 미팅으로 정보를 공유하고 피드백을 받을 수 있는 자리를 가집니다

[공부 방향]
엔지니어링이 아닌 사이언스를 목표로 하길 원합니다
따라서 인공 신경망의 가장 수학 기초인 선형대수학에 대한 이해가 필수입니다
선형대수학 책 중, [Coding The Matrix](http://www.kyobobook.co.kr/product/detailViewKor.laf?ejkGb=KOR&mallGb=KOR&barcode=9791195149292) 이 책이 개발자로써 이해하기 가장 쉬운 책으로 알고 있습니다. 이 책에 대한 진행 계획도 필요하다고 생각합니다
그리고 머신러닝에 관한 책은 주말에 모두가 시간이 괜찮을 때 위 운영 방향에서 제시한 것 처럼 2~3시간정도 서점 혹은 도서관에 가서 모두가 만족할 만한 책으로 진행하는 것이 좋다고 생각합니다. 첫 모임때 본 딥러닝 책도 더할 나위 없이 좋지만 더 좋은 책이 있을 수 있기에 제안드립니다. 하지만 이 선정 과정이 너무 번거롭다고 생각 될 경우 첫 모임 때 봤던 책으로 진행하는것도 찬성합니다

[진도 설정]
위 운영방향, 공부방향에서 쓴 내용들과 중복되는 내용이여서 생략하겠습니다

**Comment by dltkr77** [comment]
- 운영 방향
    1. 최소 2 ~ 3주에 1회씩은 스터디 모임을 진행.
    2. 각 개인은 준비가 미흡하더라도 무조건 모임마다 발표를 진행. (처음에는 열정적으로 하다가 점차 준비를 하지 않는 요인 제거)
    3. 진도가 다소 늦어지는 한이 있더라도, 중요한 부분은 모두가 이해하고 넘어갔으면 함.

- 공부 방향
    1. 지금과 같이 본인이 자유롭게 주제를 선정하여 학습 및 발표
    2. 1번 항목을 위해서 공통적으로 알아야 하는 부분들은 모두가 함께 공부 및 발표가 필요하다고 생각함. 예를 들어 수학, 기초적인 머신러닝 알고리즘 담당이 따로 정해진 것이 아니라, 모두가 공부해야 할 것 같음.
    3. 2번 항목을 위해서는 공부할 책을 선정하여 끝까지 읽는 것이 필요하다고 생각함.
    4. 모두가 기초 지식이 쌓인 후에는 이것 저것 해볼 수 있을 듯.

- 진도 설정
    1. 함께 선정한 책의 챕터를 적절한 양으로 협의하여 공부 및 확인
    2. 책을 끝까지 읽은 후부터는 본인이 방향을 잡고, 공부 및 발표

제 생각은 위와 같습니다. 나머지 2명도 Comment가 달리면 슬랙 채널을 통하여 협의를 하면 될 것 같습니다.

**Comment by ttamna** [comment]
운영 방향
  - 도서관 가서 책 훑어보고 스터디할 책 고르는거 찬성
    그리고 고를책은 공통적으로 공부할책(기초체력) + @(흥미를 끄는거) 골라서 내용 파고, @로 읽은 책은 리뷰 하면 좋을 듯

**Comment by ttamna** [comment]
## 운영 방향
  - 일단 초반에
    - 도서관 가서 책 훑어보고 스터디할 책 고르는거 찬성
    - 그리고 고를책은 공통적으로 공부할책(기초체력) + @(흥미를 끄는거) 골라서 내용 파고, @로 읽은 책은 리뷰 하면 좋을 듯
  - 이후 기초 체력 생기면, 다양한 프로젝트들 리뷰
  - 그리고 중간에 나오는 아이디어는 마인드스톰처럼 하찮은 것도 막 던져서 모아놓기(팀 아이디어 뱅크)
## 공부 방향
  - 엔지니어 말고 사이언티스트가 되자는 말 100퍼센트 동감
  - Nature of code 부제 처럼 현실의 세계를 디지털 세계로 옮기는 일이 매우 재밌을 것 같다는 생각(그래서 이 책은 다 같이 읽고 팀원들이 같은 비전을 가지면 좋을것 같다는 생각-우리팀의큰방향?)(개인의 자유)
  - 그래서 물리, 수학, 알고리즘 처럼 필요한 지식들은 깊이 체득하는 것을 목표로
## 진도 설정
  - 너무 빡빡하면 힘들고, 느슨하면 흥미가 떯어지는 난제, 흥미랑 긴장감을 잃지 않는 적절한 수준을 같이 고민해보고 설정하고, 하면서 조정해야 할듯.

**Comment by hackpupu** [comment]
* 의견
i. 마인드 맵 만들기(공통으로 쓸 수 있는)
ii. 용어 집 만들기(동의했던걸로 기억)
iii. 원격으로 편하게 데이터를 테스트 할 수 있는 환경 만들기?(스파크, 제플린, 텐서? 등등..?)

[운영 방향]
i. 2~3주에 1회씩 스터디 모임 진행
ii. 모임마다 모두 다 발표 진행(Github에 발표자료 업로드 후 모임)
iii. 3월이내 까지 각자의 아이디어 관련 Topic 또는 책 등을 리뷰
iv. 책 선정(종류는 제한이 없었으면 함. 범위는 머신러닝/데이터사이언스/딥러닝/수학 으로 제한)

[공부 방향]
i. 자신의 자율주제 발표 (선택)
ii. 진도에 대한 발표(필수)
iii. 발표자료에 대해선 100% 문서화(Blog 또는 git.io 또는 Slide 형식 선택)
iv. 서로가 모두 이해할 수 있도록 자료화 목표로 함.(기초~고급?)

[진도 설정]
i. 선정된 책에 대해 협의
ii. 추후, 책을 다 리뷰한다면 논문 등에 대해서 협의 및 리뷰(논문은 hackpupu가 한정되게 무료 다운가능)
iii. 2달이내에는 책 한권을 끝낼 수 있게 진도 설정이 되면 함.

**Comment by hackpupu** [comment]
[책 순서]
1. Coding the Matrix + Nature of Code(중반부)
2. 머신러닝 인 액션 + Nature of Code(후반부)
3. 밑바닥부터 시작하는 딥 러닝

[모임 발표]
- 발표자는 랜덤픽(각자, 짜온 프로그램으로 발표)
1. 기본적으로 책 진도 관련 발표. (2가지 발표자료 준비, Coding the Matrix, Nature of code)
2.  +@로 자신이 하고싶은 발표는 자유
3. 발표내용의 경우, 서로를 이해시키기 위한 노력은 담되 모르는 부분에 대해 정확히 짚을 수 있는 토론시간이 많을 수 있도록 준비

[책 진도]
- cd80 의견: Coding the Matrix 챕터2, Nature of Code 챕터2
- 우선은, 각자 두 책에 대해 리뷰를 해 봐야될꺼 같고 다음주 화(01/31)까지 의견 제시
